/* statement to select version, database user and database name */
select version(), user(), database();

/* SELECT CLAUSE */
/* select clause can give, besides data included in the table,
include additional columns, that can be anything */
select language_id,
  'COMMON' as language_usage, /* data {optional as} column_alias_name */
  language_id * 3.14 lang_pi_value, /* `as` keyword can be omited */
  upper(name) language_name
from language;

/* DISTINCT TO FETCH UNIQUE VALUES */
/* big list of all actor ids which repeat */
/* 5462 rows */
select actor_id
from film_actor
order by actor_id;

/* 200 rows */
select distinct actor_id
from film_actor
order by actor_id;

/* same thing as not specifying distinct */
/* 5462 rows */
select all actor_id
from film_actor
order by actor_id;

/* FROM CLAUSE */
/* The from clause defines the tables used by a query, along with the means of linking the
tables together. */
/* from can be used on:
hard tables
derived tables
temporary tables
virtual tables */

/* example usage on a derived table using subquery
derived table is a table generated by a subquery
table returned from the subquery is queried again */
select concat (cust.last_name, ' ', cust.first_name) full_name
from (select first_name, last_name from customer where first_name = 'jessie') cust;

/* temporary table is a table that is going to disappear after a session */
create temporary table actors_j (
actor_id smallint(5),
first_name varchar (45),
last_name varchar (45)
);

insert into actors_j
select actor_id, first_name, last_name /* data insertion and select can be combined */
from actor
where last_name like 'J%';

select * from actors_j;

/* view is a query that pretends to be a table
views don't store any actual data, and instead they reuse existing data */
create view cust_vw as
select customer_id, first_name, last_name, active
from customer;

select * from cust_vw;

/* table links and inner join */
select customer.first_name, customer.last_name, time(rental.rental_date) rental_time
from customer
inner join rental
on customer.customer_id = rental.customer_id
where date(rental.rental_date) = '2005-06-14';

/* table aliases: same query, but shorter to write */
select c.first_name, c.last_name, time(r.rental_date) rental_time
from customer c
inner join rental r
on c.customer_id = r.customer_id
where date(r.rental_date) = '2005-06-14';

/* WHERE CLAUSE */
/* used for filtering of rows */
select title
from film
where rating = 'G' and rental_duration >= 7;

select title, rating, rental_duration
from film
where (rating = 'G' and rental_duration >= 7)
  or (rating = 'PG-13' and rental_duration < 4)

/* GROUP BY AND HAVING CLAUSES */
/* group by creates groups based on columns */
/* having is used for filtering groups, it is applied AFTER where clause */
select c.first_name, c.last_name, count(*)
from customer c
inner join rental r
on c.customer_id = r.customer_id
group by c.first_name, c.last_name
having count(*) >= 40;

/* ORDER BY CLAUSE */
/* once can order rows by more than one field */
select c.first_name, c.last_name,
  time(r.rental_date) rental_time
from customer c
inner join rental r
on c.customer_id = r.customer_id
where date(r.rental_date) = '2005-06-14'
 /* order of columns matter*/
order by c.last_name, c.first_name;

/* order can be ascending or descending */
select c.first_name, c.last_name,
  time(r.rental_date) rental_time
from customer c
inner join rental r
on c.customer_id = r.customer_id
where date(r.rental_date) = '2005-06-14'
/* can be asc or desc */
order by rental_time desc;

select c.first_name, c.last_name,
  time(r.rental_date) rental_time
from customer c
inner join rental r
on c.customer_id = r.customer_id
where date(r.rental_date) = '2005-06-14'
/* instead of specifying name of the column,
it's position in select clause can be used instead */
order by 3 desc;
